### ISSUE TITLE
Traefik v2 support

### ISSUE THREAD

**Issue by max-baz** [jovobe/mailcow-traefik-acme-adapter#5]
Hey, I think this needs to be adjusted for traefik v2, I haven't looked much into details yet but I can see that the `acme.json` format is different now, the `dumpcerts.sh` script is gone (they say to use https://github.com/ldez/traefik-certs-dumper instead), and maybe something else has changed.

Will you be able to look into this? :)

**Comment by jovobe** [comment]
Yeah, I just realized this today. I think I won't be able to look into this in the near future. I decided to stay on 1.7 for the moment. But pull requests are welcome at any time ;)

**Comment by max-baz** [comment]
OK 👍 I've started to look into migrating to v2, but maaan it's a lot of work! If I manage to get to this before you do, I will send the PR 😉

**Comment by jovobe** [comment]
Yeah, that scared me too :D Nice, I am looking forward to it!

**Comment by kereis** [comment]
Sorry for possible necroposting. It seems like you haven't taken care of Traefik v2 yet.
If you still need a Docker image, I just created one based of https://github.com/ldez/traefik-certs-dumper and mailu/traefik-certdumper.

https://github.com/humenius/traefik-certs-dumper

If I did not notice that, then I'm sorry in advance. :D

**Comment by max-baz** [comment]
I have recently gotten to finally upgrade to Traefik v2, and I confirm that @humenius's repo works well. I think it makes sense to combine our efforts instead of having several repos doing the same thing, so I will close the issue. 

Thanks to both of you @jovobe and @humenius for your help!
